version: '2'

networks:
  app-tier:
    driver: bridge

services:
  mongo:
    image: bitnami/mongodb
    ports:
      - 27017:27017
    networks:
      - app-tier

  elasticsearch:
    image: 'bitnami/elasticsearch:latest'
    networks:
      - app-tier
    volumes:
      - ./elasticsearch:/bitnami/elasticsearch
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    links:
      - mongo:mongo
      - elasticsearch:elasticsearch
    networks:
      - app-tier
